### PR TITLE
feat: upgrade supported AWSCC type with DDB table

### PR DESCRIPTION
**Pull request by ryancormack**
Added the now supported by AWS CC DynamoDB Table type. https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/supported-resources.html

Fixes #

### CODE REVIEW

**Review by ansgarm — APPROVED** [review]
Thanks @ryancormack 👍

**Comment by ryancormack** [comment]
@ansgarm Noticed this file was autogenerated, so I've fully updated all the current types using the script

**Comment by ansgarm** [comment]
Good catch 😁 I did the same in https://github.com/hashicorp/cdktf-aws-cdk/pull/96 😄

**Comment by ansgarm** [comment]
But let's wait for yours to complete CI, so your contribution can be valued here 😁👍

**Pull request merged**
