### PR TITLE
feat!: stop using manual mappings for `EC2::EIP`, `EC2::NatGateway`, `EC2::InternetGateway`, `ElasticLoadBalancingV2::TargetGroup` and update supported resource types

### PR DESCRIPTION
**Pull request by skorfmann**
This updates the list of supported resource types of the cloud control api and removes obsolete mappings.

### CODE REVIEW

**Review by ansgarm — COMMENTED** [review]
Looks good! I just noticed that the supported types change between regions 😬 Which region did you run that with?
If I'm using `us-east-1` I'm getting almost the same result as you, except for `AWS::S3::MultiRegionAccessPoint` (which would be removed).

**Comment by ansgarm** [comment]
Updated the title to include a `!` as stopping using manual mappings is technically a breaking change as it will delete and re-create resources as the underlying Terraform resource changes. Users will need to manually stop tracking resources through Terraform and import them into the new resource type.

**Comment by skorfmann** [comment]
> Looks good! I just noticed that the supported types change between regions 😬 Which region did you run that with?
> If I'm using `us-east-1` I'm getting almost the same result as you, except for `AWS::S3::MultiRegionAccessPoint` (which would be removed).

Yes, noticed that as well. e.g. in eu-central-1 are about 50 resource types missing. Used `us-east-1` and ignored the removed resource :) I'm assuming this was originally fetched from `us-east-2` or something?

**Comment by ansgarm** [comment]
Ah, got it! Makes sense
As I haven't paid attention to the region in the past, I suspect that some default region on my machine was used – although none appears to be set 😅

**Review by ansgarm — APPROVED** [review]

**Pull request merged**
